### PR TITLE
Ability to exclude fields from export

### PR DESCRIPTION
**Pull request by jacksleight**
As discussed on Discord.

I've left this draft as although I think it would be a useful feature I'm not 100% sure on the best way to implement it. At the moment you add `csv_exporter: false` to any fields you don't want to included. But there could be other ways to do it:

* Should the key be more generic, like `exportable: false`
* Should the condition be flipped: `unexportable: true`
* Should this information be in a config file rather than the yaml blueprints
* Should there be a UI option to override this and still export everything
* Other things I've not even thought of...

I'll leave it to your judgement to decide how (or if) you want to implement this. Can make any changes if necessary.

### CODE REVIEW

**Comment by duncanmcclean** [comment]
Thanks for this!

I think we should probably have an array of excluded fields in a config file, instead of adding bits to fields in the blueprint files.

**Comment by jacksleight** [comment]
Sure, makes sense and is probably the right way to do it, the blueprint approach was just convenient 😄 .

I'll give this another go.

**Comment by jacksleight** [comment]
I've updated this to use a config file instead, format of the config is [copied from your duplicator addon](https://github.com/duncanmcclean/duplicator/blob/main/config/duplicator.php).

**Comment by duncanmcclean** [comment]
Thanks! I'm about to head off for this week but have added to my list for next week!

**Review by duncanmcclean — APPROVED** [review]
Thanks again for this - sorry it's taken me so long to get this merged in!

I've made a couple of changes:

* Renamed the config file to `statamic-csv-exporter.php` - I like being explicit about where the CSV exporter is in case you're do lots of CSV exports in a Laravel app, install this addon, then get confused what the config file is for.
* Changed the key inside the config file from `entries` to `collections`
* Added some documentation

Have a great rest of your day!

**Pull request merged**
